Models/Auto.cs
using System;
using System.Collections.Generic;

namespace CRUDAutosv.Models;

public partial class Auto
{
    public int IdAuto { get; set; }

    public string Marca { get; set; } = null!;

    public string Modelo { get; set; } = null!;

    public string Color { get; set; } = null!;

    public string Patente { get; set; } = null!;

    public short Anio { get; set; }
}

Models/AutosContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CRUDAutosv.Models;

public partial class AutosContext : DbContext
{
    public AutosContext()
    {
    }

    public AutosContext(DbContextOptions<AutosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Auto> Autos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) { }
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
      //  => optionsBuilder.UseSqlServer("server=GP-LAPTOPV2; database=Autos; integrated security=true; TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Auto>(entity =>
        {
            entity.HasKey(e => e.IdAuto).HasName("PK__Autos__D8600DCFFE53EC3F");

            entity.Property(e => e.IdAuto)
                .ValueGeneratedNever()
                .HasColumnName("idAuto");
            entity.Property(e => e.Color).HasMaxLength(255);
            entity.Property(e => e.Marca).HasMaxLength(255);
            entity.Property(e => e.Modelo).HasMaxLength(255);
            entity.Property(e => e.Patente).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Models/ErrorViewModel.cs
namespace CRUDAutosv.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AutoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUDAutosv.Models;

namespace CRUDAutosv.Controllers
{
    public class AutoesController : Controller
    {
        private readonly AutosContext _context;

        public AutoesController(AutosContext context)
        {
            _context = context;
        }

        // GET: Autoes
        public async Task<IActionResult> Index(string Search, int anio)

        {
            //Realizamos la condición para filtrar por Modelo, Marca y año
            var autos = from auto in _context.Autos select auto;

            if (!String.IsNullOrEmpty(Search))
            {
                   autos = autos.Where(e => e.Marca!.Contains(Search) || e.Modelo!.Contains(Search) || e.Anio.ToString().Contains(Search));
            }
          

            return View(await autos.ToListAsync()); 
                        
        }

        // GET: Autoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Autos == null)
            {
                return NotFound();
            }

            var auto = await _context.Autos
                .FirstOrDefaultAsync(m => m.IdAuto == id);
            if (auto == null)
            {
                return NotFound();
            }

            return View(auto);
        }

        // GET: Autoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Autoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAuto,Marca,Modelo,Color,Patente,Anio")] Auto auto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(auto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(auto);
        }

        // GET: Autoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Autos == null)
            {
                return NotFound();
            }

            var auto = await _context.Autos.FindAsync(id);
            if (auto == null)
            {
                return NotFound();
            }
            return View(auto);
        }

        // POST: Autoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAuto,Marca,Modelo,Color,Patente,Anio")] Auto auto)
        {
            if (id != auto.IdAuto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(auto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutoExists(auto.IdAuto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(auto);
        }

        // GET: Autoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Autos == null)
            {
                return NotFound();
            }

            var auto = await _context.Autos
                .FirstOrDefaultAsync(m => m.IdAuto == id);
            if (auto == null)
            {
                return NotFound();
            }

            return View(auto);
        }

        // POST: Autoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Autos == null)
            {
                return Problem("Entity set 'AutosContext.Autos'  is null.");
            }
            var auto = await _context.Autos.FindAsync(id);
            if (auto != null)
            {
                _context.Autos.Remove(auto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AutoExists(int id)
        {
          return (_context.Autos?.Any(e => e.IdAuto == id)).GetValueOrDefault();
        }
    }
}

Controllers/HomeController.cs
using CRUDAutosv.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRUDAutosv.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Autoes/Create.cshtml
@model CRUDAutosv.Models.Auto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Auto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdAuto" class="control-label"></label>
                <input asp-for="IdAuto" class="form-control" />
                <span asp-validation-for="IdAuto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patente" class="control-label"></label>
                <input asp-for="Patente" class="form-control" />
                <span asp-validation-for="Patente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Autoes/Delete.cshtml
@model CRUDAutosv.Models.Auto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Auto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Patente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Patente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdAuto" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Autoes/Details.cshtml
@model CRUDAutosv.Models.Auto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Auto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Patente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Patente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdAuto">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Autoes/Edit.cshtml
@model CRUDAutosv.Models.Auto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Auto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdAuto" />
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patente" class="control-label"></label>
                <input asp-for="Patente" class="form-control" />
                <span asp-validation-for="Patente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Autoes/Index.cshtml
@model IEnumerable<CRUDAutosv.Models.Auto>

@{
    ViewData["Title"] = "Index";
}
<div class="text-center">
    <h1 class="display-3">Autos Por Chile</h1>
    <p>
        <a asp-action="Create" class="link-offset-2 link-underline link-underline-opacity-0">Almacena un nuevo auto</a>
    </p>
</div>


<div>
    <div>
    <form action="/Autoes" method="get">
            <div >
                <div class="input-group mb-3">
                    <input class="form-control" type="search" placeholder="Chevrolet | Versa | 2020" name="Search" class="input w-full border mt-2" />
                    <button type="submit" class="btn btn-outline-secondary" id="button-addon2">Filtrar</button>
                </div>

                
        </div>
    </form>
</div>
</div>
<div class="text-center">
<table class="table table-striped table-hover table-responsive">
    <thead >
        <tr >
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patente)
            </th>
            <th>
                Año
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Patente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Anio)
            </td>
            <td>
                    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.IdAuto">Editar</a> |
                    <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.IdAuto">Detalles</a> |
                <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.IdAuto">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
    
</table>
</div>
<a asp-action="Index" class="btn btn-primary">Volver</a>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDAutosv</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUDAutosv.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUDAutosv</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autoes" asp-action="Index">CRUDAutos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CRUDAutosv - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>